
---
title: "All Australia Benzo and Opioid Basic Stats"
author:  "Mofi Islam and Dennis Wollersheim "
date: "2018-04-30"
output:
workflowr::wflow_html:
toc: false
---

```{r pre_initial, echo=FALSE, results='hide', message=FALSE, warning=FALSE}

rm(list=ls())
options(width = 200)
show_code = FALSE
source("lib/functions.R")
source("lib/mapping_functions.R")
source("lib/mapping_paper.R")
source("lib/standardisation.R")
source("lib/get_data.R")
source("lib/generate_data_frames.R")
library('tidyverse')
opts_chunk$set(echo = FALSE)
opts_chunk$set(fig.width=12, fig.height=8)

```

# load in data

```{r load, results='hide', message=FALSE, warning=FALSE}


foreign::read.dta( '../benzodiazepine/data/nobackup/match_multiyear.v2.dta') %>% 
  as_tibble() %>%
  { . } -> df_my


foreign::read.dta( '../benzodiazepine/data/nobackup/match_single_period.v1.dta') %>% 
  as_tibble() %>%
  { . } -> df_sp


```


## summarise the multiyear data

```{r}

  df_my %>%
  group_by( pin) %>%
  summarise( ndays = sum(ndays)) %>% 
  { . } -> df_my_sum

```

## merge and compare the multiyear and single year data

```{r}


df_sp %>%
  summarise( sum( ndays))

df_my %>%
  summarise( sum( ndays))

```

## compare individual peeople
One error, person had duplicate drug of choice

```{r}

df_sp %>%
  select( pin, ndays) %>%
  inner_join( df_my_sum, by='pin') %>% 
  { . } -> df_joined

df_joined %>% 
  filter( ndays.x != ndays.y)

df_sp %>%
  filter( pin == '2630699530') %>% 
  select( doc_benzo)


```
